namespace:
  name: staging
replicaCount: 1
deployName: nginx-staging
image:
  name: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
service:
  port: 80
  type: ClusterIP
configMap:
  versionKey: version
  versionValue: 1.18.0