namespace:
  name: prod
replicaCount: 2
deployName: nginx-prod
image:
  name: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "70m"
    memory: "256Mi"
service:
  port: 80
  type: ClusterIP
configMap:
  versionKey: version
  versionValue: 1.17.0