namespace:
  name: demo
replicaCount: 3
image:
  name: nginx
  tag: alpine
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
service:
  port: 8111
  type: ClusterIP
configMap:
  versionKey: version
  versionValue: alpine