apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.image.name }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.deployName }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
      tag: {{ .Values.image.tag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.deployName }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}